services:
    watchtower:
        image: percona/watchtower
        container_name: watchtower
        environment:
        - DOCKER_API_VERSION=1.52
        - DOCKER_HOST=unix:///var/run/docker.sock
        - WATCHTOWER_POLL_INTERVAL=60
        - WATCHTOWER_CLEANUP=true
        - WATCHTOWER_INCLUDE_RESTARTING=true
        - WATCHTOWER_NO_STARTUP_MESSAGE=true
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock


    express-app:
        image : k13lucien/express-app
        container_name: express-app
        ports:
            - 8080:8080
